application:
  name: "Bidoyon+"
  host: "localhost"
  port: 8080
  local_address: "http://localhost:8080"
  external_address: "http://localhost:8080"
database:
  file_path: "database.db"
  scripts_folder: "sql/"
logger:
  format: "%(levelname)s: %(message)s"
  file: "logs.txt"
permissions:
  SUPER: 0
  ADMIN: 1
  MANAGER: 2
  USER: 3
contact:
  name: BidulaxStudio
  github: "https://github.com/BidulaxStudio"
  mail:
    address: "contact@bidulaxstudio.eu"
    subject: "A propos de Bidoyon+"
    body: "Je vous contacte depuis l'application Bidoyon+ !"